<a href="https://colab.research.google.com/github/vitm31/Python_Practice/blob/master/Numpy%26pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
d = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
print('Original dictionary : ',d)
sorted_d = sorted(d.items())
print(sorted_d)


Original dictionary :  {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
[(0, 0), (1, 2), (2, 1), (3, 4), (4, 3)]


In [4]:
Sample_Dictionary={0:10, 1:20}
Sample_Dictionary[2]=30
print(Sample_Dictionary)

{0: 10, 1: 20, 2: 30}


In [8]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4={}
dic4.update(dic2.update(dic3))
print(dic4)

TypeError: ignored

In [11]:
dic1.update(dic2)
print(dic1)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [14]:
if 2 in dic1.keys():
  print("yes")

yes


In [16]:
d = {'x': 10, 'y': 20, 'z': 30}
d.values()

dict_values([10, 20, 30])

In [18]:
for key,value in d.items():
  print(key,value)

x 10
y 20
z 30


In [22]:
n=int(input("Enter any number"))
dict={}
for x in range(1,n+1):
  dict[x]=x*x
print(dict)

Enter any number15
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [23]:
d1 = {'a': 100, 'b': 200}
d2 = {'x': 300, 'y': 200}
print(d1.update(d2))

None


In [24]:
d1

{'a': 100, 'b': 200, 'x': 300, 'y': 200}

In [25]:
my_dict = {'data1':100,'data2':-54,'data3':247}
print(sum(my_dict.values()))

293


In [26]:
myDict = {'a':1,'b':2,'c':3,'d':4}
print(myDict)
if 'a' in myDict: 
    del myDict['a']
print(myDict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}
{'b': 2, 'c': 3, 'd': 4}


In [30]:
keys=['red', 'green', 'blue']
values=['#FF0000','#008000', '#0000FF']
color_dictionary=dict(zip(keys,values))
print(color_dictionary)

TypeError: ignored

In [0]:
color_dict = {'red':'#FF0000',
          'green':'#008000',
          'black':'#000000',
          'white':'#FFFFFF'}
        

In [32]:
print(color_dict)

{'red': '#FF0000', 'green': '#008000', 'black': '#000000', 'white': '#FFFFFF'}


In [35]:
sorted(color_dict)

['black', 'green', 'red', 'white']

In [40]:
my_dict = {'x':500, 'y':5874, 'z': 560}
max(my_dict.values())

5874

In [41]:
dict1={1:"veer",2:"ram",3:"shyam",4:"veer"}
set1=set(dict1)
print(set1)

{1, 2, 3, 4}


In [42]:
from collections import Counter
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
d = Counter(d1) + Counter(d2)
print(d)

Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


In [45]:
l=[{"V":"S001"}, {"V": "S002"}, {"VI": "S001"}, {"VI": "S005"}, {"VII":"S005"}, {"V":"S009"},{"VIII":"S007"}]
print(l)



[{'V': 'S001'}, {'V': 'S002'}, {'VI': 'S001'}, {'VI': 'S005'}, {'VII': 'S005'}, {'V': 'S009'}, {'VIII': 'S007'}]


In [47]:
from collections import Counter
x = Counter({'Math':81, 'Physics':83, 'Chemistry':87})
print(x.most_common)

<bound method Counter.most_common of Counter({'Chemistry': 87, 'Physics': 83, 'Math': 81})>


In [50]:
x = {'key1': 1, 'key2': 3, 'key3': 2}
y = {'key1': 1, 'key2': 2}
for key,value in set(x.items()) and set(y.items()):
  print(key,value)

key2 2
key1 1


In [51]:
tuplex = ("tuple", False, 3.2, 1)
print(tuplex)

('tuple', False, 3.2, 1)


In [52]:
tuplex = 5, 10, 15, 20, 25
print(tuplex)
#Create a tuple of one item
tuplex = 5,
print(tuplex)

(5, 10, 15, 20, 25)
(5,)


In [53]:
tuplex = (4, 6, 2, 8, 3, 1)
tuplex+(9,)

(4, 6, 2, 8, 3, 1, 9)

In [54]:
tuplex1 = tuplex[:5] + (15, 20, 25) + tuplex[:5]
print(tuplex1)

(4, 6, 2, 8, 3, 15, 20, 25, 4, 6, 2, 8, 3)


In [55]:
print(id(tuplex))
print(id(tuplex1))

140296303840040
140296304314672


In [56]:
tup = ('e', 'x', 'e', 'r', 'c', 'i', 's', 'e', 's')
str =  ''.join(tup)
print(str)

exercises


In [57]:
tuplex = 2, 4, 5, 6, 2, 3, 4, 4, 7 
tuplex.count(4)

3

In [58]:
tuplex = ("w", 3, "r", "e", "s", "o", "u", "r", "c", "e")
print("r" in tuplex)
print(5 in tuplex)

True
False


In [63]:
tuplex = ((2, "w"),(3, "r"))
print(dict((y,x) for x,y in tuplex))

TypeError: ignored

In [64]:
t = (100, 200, 300)
print("this is a tuple:{}".format(t))

this is a tuple:(100, 200, 300)


In [68]:
num = [10,20,30,(10,20),40]
count=0
for n in num:
  if isinstance(n,tuple):
    break
  else:
    count+=1
print(count)

3


In [69]:
n = set([0, 1, 2, 3, 4])
print(n)

{0, 1, 2, 3, 4}


In [70]:
num_set = set([0, 1, 2, 3, 4, 5])
for n in num_set:
  print(n)

0
1
2
3
4
5


In [71]:
num_set.add(6)
print(num_set)

{0, 1, 2, 3, 4, 5, 6}


In [72]:
num_set.remove(6)
print(num_set)

{0, 1, 2, 3, 4, 5}


In [76]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [77]:
a[5]=6
print(a)

IndexError: ignored

In [4]:
n=[]
for x in range(1500, 2701):
    if (x%7==0) and (x%5==0):
      n.append(str(x))
print(",".join(n))

1505,1540,1575,1610,1645,1680,1715,1750,1785,1820,1855,1890,1925,1960,1995,2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695


In [10]:
import random
random.choice(range(1,10))

5

In [11]:
word = input("Input a word to reverse: ")
word[::-1]

Input a word to reverse: dog


'god'

In [14]:
 datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), 5, 12]
 for element in datalist:
   print(element)
   print(type(element))
             

1452
<class 'int'>
11.23
<class 'float'>
(1+2j)
<class 'complex'>
True
<class 'bool'>
w3resource
<class 'str'>
(0, -1)
<class 'tuple'>
5
<class 'int'>
12
<class 'int'>


In [21]:
for i in range(0,7):
  if i==3 or i==6:
    continue
  else:
    print(i)

0
1
2
4
5


In [22]:
for number in range(1,51):
  if number%3==0:
    print("fizz")
  elif number%5==0:
    print("Buzz")
  else:
    print(number)

1
2
fizz
4
Buzz
fizz
7
8
fizz
Buzz
11
fizz
13
14
fizz
16
17
fizz
19
Buzz
fizz
22
23
fizz
Buzz
26
fizz
28
29
fizz
31
32
fizz
34
Buzz
fizz
37
38
fizz
Buzz
41
fizz
43
44
fizz
46
47
fizz
49
Buzz


In [24]:
numbers=input("Enter any 5 binary numbers")
number=int(numbers,2)
for number in numbers:
  if number%5==0:
    print(number)

Enter any 5 binary numbers0100,0011,1010,1001,1100,1001


ValueError: ignored

In [27]:
s=input("Enter any string")
d=l=0
for c in s:
  if c.isdigit():
    d+=1
  elif c.isalpha():
    l+=1
print(l,d)

Enter any stringpython3.2
6 2


In [28]:
import re
p= input("Input your password")
x = True
while x:  
    if (len(p)<6 or len(p)>12):
        break
    elif not re.search("[a-z]",p):
        break
    elif not re.search("[0-9]",p):
        break
    elif not re.search("[A-Z]",p):
        break
    elif not re.search("[$#@]",p):
        break
    elif re.search("\s",p):
        break
    else:
        print("Valid Password")
        x=False
        break

if x:
    print("Not a Valid Password")

Input your passwordhjj9
Not a Valid Password


In [32]:
for i in range(100,401):
  i_new=str(i)
  if int(i_new[0]%2==0) and int(i_new[1]%2==0) and int(i_new[2]%2==0):
    print(i_new)


TypeError: ignored

In [35]:
h_age = int(input("Input a dog's age in human years: "))

if h_age < 0:
	print("Age must be positive number.")
	exit()
elif h_age <= 2:
	d_age = h_age * 10.5
else:
	d_age = 21 + (h_age - 2)*4

print("The dog's age in dog's years is", d_age)

Input a dog's age in human years: 5
The dog's age in dog's years is 33


In [36]:
l = input("Input a letter of the alphabet: ")

if l in ('a', 'e', 'i', 'o', 'u'):
	print("%s is a vowel." % l)
elif l == 'y':
	print("Sometimes letter y stand for vowel, sometimes stand for consonant.")
else:
	print("%s is a consonant." % l)

Input a letter of the alphabet: z
z is a consonant.


In [37]:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 
x: 5
y: 6
z: 5
isosceles triangle


In [38]:
5 in range(6)

True

In [49]:
s="The quick Brow Fox"
d={"u":0,"l":0}
for c in s:
  if c.upper():
    d["u"]+=1
  elif c.lower():
    d["l"]+=1
  else:
    pass
print(d["u"],d["l"])
print(d)

18 0
{'u': 18, 'l': 0}


In [47]:
for c in s:
  if c.upper():
    print(c)


T
h
e
 
q
u
i
c
k
 
B
r
o
w
 
F
o
x


In [0]:
def sq(x):
  return x*x

In [51]:
print(list(map(sq,range(1,31))))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [52]:
print(list(map(lambda x:x*x,range(1,31))))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [55]:
import time
import datetime
print(datetime.datetime.now())

2019-12-06 09:38:33.735476


In [57]:
print(datetime.date.today())

2019-12-06


In [62]:
import time
import numpy as np
size_of_vec = 1000000
start_time=time.time()
list1=range(size_of_vec)
list2=range(size_of_vec)
sum_=[list1[i]+list2[i] for i in range(len(list1))]
python_time=time.time()-start_time
numpy_start_time=time.time()
array1=np.arange(size_of_vec)
array2=np.arange(size_of_vec)
sum_numpy=array1+array2
numpy_time=time.time()-numpy_start_time
print("python time is:{}".format(python_time))
print("numpy time is:{}".format(numpy_time))
print("numpy is faster by:{}".format(python_time/numpy_time))

python time is:0.2943451404571533
numpy time is:0.006417036056518555
numpy is faster by:45.86932937023964


In [63]:
array=np.array([1,2,3,4,5])
print(type(array))
print(array.dtype)

<class 'numpy.ndarray'>
int64


In [64]:
my_mat = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]        # Creating a 2D list or list of lists
print(my_mat)
mat=np.array(my_mat)
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
mat.shape

(4, 3)

In [69]:
print(mat.ndim)
print(mat.dtype)

2
int64


In [71]:
print(np.arange(0,10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [73]:
print(np.zeros((3,3)))
print(np.ones((2,2)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [75]:
print(np.ones((3,3)).ndim)

2


In [76]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [81]:
print(np.random.rand(5))
print(np.random.rand(4,4))
nine_array=np.random.randn(9)
print(nine_array)

[0.76024984 0.87210396 0.86633616 0.00506025 0.67008849]
[[0.68464905 0.46329275 0.35972936 0.41617647]
 [0.40699631 0.69512584 0.53939365 0.03933088]
 [0.58493574 0.06929983 0.41214314 0.62562419]
 [0.54267461 0.2922567  0.04753318 0.79180856]]
[-0.68906652 -0.46728626  0.15562568 -0.27000996  0.49910335 -0.49094562
  2.44812158  0.93671781  0.30348017]


In [82]:
nine_array.reshape(3,3)

array([[-0.68906652, -0.46728626,  0.15562568],
       [-0.27000996,  0.49910335, -0.49094562],
       [ 2.44812158,  0.93671781,  0.30348017]])

In [83]:
array

array([1, 2, 3, 4, 5])

In [87]:
array[1:4]=-15
print(array)

[-17 -15 -15 -15 -17]


In [88]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [89]:
print(array_2d[0,2])
print(array_2d[:2,:2])
print(array_2d[1:3,1:])

3
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [90]:
array_cond=np.arange(1,15)
print(array_cond)
print(array_cond>8)
print(array_cond[array_cond>8])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[False False False False False False False False  True  True  True  True
  True  True]
[ 9 10 11 12 13 14]


In [91]:
array_1d=np.array([1,2,3])
print(array_1d)
print(array_2d)

[1 2 3]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [92]:
print(array_2d+array_1d)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [93]:
print(array_2d+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [94]:
print(array_1d.max())
print(array_2d.min())

3
1


In [98]:
print(array_1d.argmax())
print(array_2d.argmin())
print(np.median(array_2d))
print(np.mean(array_2d))

2
0
6.5
6.5


In [99]:
print(np.sqrt(array_2d))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162]]


In [100]:
array

array([-17, -15, -15, -15, -17])

In [102]:
array=np.arange(1,17)
print(array.reshape(4,4))
print(array.flatten())
print(array.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [103]:
array_x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array_y=np.array([[20,21,22],[23,24,25],[26,27,28],[29,30,31]])
print(array_x)
print(array_y)
print(np.concatenate((array_x,array_y),axis=1))
print(np.concatenate((array_x,array_y),axis=0))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]
[[ 1  2  3 20 21 22]
 [ 4  5  6 23 24 25]
 [ 7  8  9 26 27 28]
 [10 11 12 29 30 31]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


In [106]:
z=np.concatenate((array_x,array_y),axis=1)
print(z)
print(np.hsplit(z,2))
print(np.vsplit(z,2))

[[ 1  2  3 20 21 22]
 [ 4  5  6 23 24 25]
 [ 7  8  9 26 27 28]
 [10 11 12 29 30 31]]
[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])]
[array([[ 1,  2,  3, 20, 21, 22],
       [ 4,  5,  6, 23, 24, 25]]), array([[ 7,  8,  9, 26, 27, 28],
       [10, 11, 12, 29, 30, 31]])]


In [0]:
import numpy as np
import pandas as pd

In [3]:
country=["India","England","France"]
Capitals=["Delhi","London","Paris"]
array=np.array(Capitals)
Dict={"a":10,"b":20,"c":30,"d":40}
print(pd.Series(array))
print(pd.Series(Dict))
print(pd.Series(data=Capitals,index=country))
print(pd.Series(data=Capitals))

0     Delhi
1    London
2     Paris
dtype: object
a    10
b    20
c    30
d    40
dtype: int64
India       Delhi
England    London
France      Paris
dtype: object
0     Delhi
1    London
2     Paris
dtype: object


In [5]:
my_series=pd.Series({'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80})
print(my_series)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64


In [8]:
print(my_series.shape)
print(my_series[3])
print(my_series[3:7])
print(my_series[["d","e","f"]])
print(my_series+my_series)

(8,)
40
d    40
e    50
f    60
g    70
dtype: int64
d    40
e    50
f    60
dtype: int64
a     20
b     40
c     60
d     80
e    100
f    120
g    140
h    160
dtype: int64


In [13]:
Fruits=["apple","banana","kiwi","orange"]
fruits_df=pd.DataFrame(Fruits,columns=["Fruit"])
print(fruits_df)

    Fruit
0   apple
1  banana
2    kiwi
3  orange


In [14]:
people=[["veer",35,"ab+ve"],["khusbu",32,"b+ve"],["srija",4,"ab+ve"]]
people_df=pd.DataFrame(people,columns=["Name","Age","Blood group"])
print(people_df)

     Name  Age Blood group
0    veer   35       ab+ve
1  khusbu   32        b+ve
2   srija    4       ab+ve


In [15]:
people={"Name":["veer","khusbu","srija"],"Age":[35,32,4],"Blood_group":["ab+ve","b+ve","ab+ve"]}
people_df=pd.DataFrame(people)
print(people_df)

     Name  Age Blood_group
0    veer   35       ab+ve
1  khusbu   32        b+ve
2   srija    4       ab+ve


In [3]:
import pandas as pd
csv_df=pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.csv")
csv_df


ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA   Richvalley        20

[6 rows x 7 columns]

In [4]:
json_df=pd.read_json("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.json")
json_df

ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA   Richvalley        20

[6 rows x 7 columns]

In [5]:
excel_df=pd.read_excel('https://github.com/insaid2018/Term-1/blob/master/Data/Casestudy/supermarkets.xlsx?raw=true', sheet_name=0)
excel_df

ID          Address  ... Supermarket Name Number of Employees
0   1     3666 21st St  ...          Madeira                   8
1   2   735 Dolores St  ...      Bready Shop                  15
2   3      332 Hill St  ...      Super River                  25
3   4     3995 23rd St  ...       Ben's Shop                  10
4   5  1056 Sanchez St  ...          Sanchez                  12
5   6  551 Alvarado St  ...       Richvalley                  20

[6 rows x 7 columns]

In [6]:
txt_df=pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets-semi-colons.txt', sep=';')
txt_df

ID          Address           City  ... Country          Name Employees
0   1     3666 21st St  San Francisco  ...     USA       Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA   Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA   Super River        25
3   4     3995 23rd St  San Francisco  ...     USA    Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA       Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA    Richvalley        20

[6 rows x 7 columns]

In [7]:
people_df

NameError: ignored

In [8]:
csv_df

ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA   Richvalley        20

[6 rows x 7 columns]

In [12]:
print(csv_df.shape)
print(csv_df.dtypes)
print(csv_df.info())
print(csv_df.index)
print(csv_df.columns)
print(csv_df.count())

(6, 7)
ID            int64
Address      object
City         object
State        object
Country      object
Name         object
Employees     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
ID           6 non-null int64
Address      6 non-null object
City         6 non-null object
State        6 non-null object
Country      6 non-null object
Name         6 non-null object
Employees    6 non-null int64
dtypes: int64(2), object(5)
memory usage: 464.0+ bytes
None
RangeIndex(start=0, stop=6, step=1)
Index(['ID', 'Address', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')
ID           6
Address      6
City         6
State        6
Country      6
Name         6
Employees    6
dtype: int64


In [15]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print(a.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]


In [16]:
import pandas as pd
people = {'Name':['Rick', 'Morty', 'Summer', 'Beth'], 'Age':[60,10,45,18], 'Blood Group':['O+','O+','A-','B+']}
people_df = pd.DataFrame(people)       
people_df

Name  Age Blood Group
0    Rick   60          O+
1   Morty   10          O+
2  Summer   45          A-
3    Beth   18          B+

In [19]:
print(people_df["Name"])
print(people_df[["Name","Age"]])

0      Rick
1     Morty
2    Summer
3      Beth
Name: Name, dtype: object
     Name  Age
0    Rick   60
1   Morty   10
2  Summer   45
3    Beth   18


In [20]:
people_df["Score"]=[10,20,30,40]
print(people_df)

     Name  Age Blood Group  Score
0    Rick   60          O+     10
1   Morty   10          O+     20
2  Summer   45          A-     30
3    Beth   18          B+     40


In [21]:
people_df["Value"]=people_df["Score"]+people_df["Age"]
people_df

Name  Age Blood Group  Score  Value
0    Rick   60          O+     10     70
1   Morty   10          O+     20     30
2  Summer   45          A-     30     75
3    Beth   18          B+     40     58

In [23]:
people_df.drop("Score",axis=1,inplace=True)
people_df

Name  Age Blood Group  Value
0    Rick   60          O+     70
1   Morty   10          O+     30
2  Summer   45          A-     75
3    Beth   18          B+     58

In [26]:
del people_df["Value"]

KeyError: ignored

In [27]:
people_df

Name  Age Blood Group
0    Rick   60          O+
1   Morty   10          O+
2  Summer   45          A-
3    Beth   18          B+

In [31]:
new_df=people_df.set_index("Name")
people_df

Name  Age Blood Group
0    Rick   60          O+
1   Morty   10          O+
2  Summer   45          A-
3    Beth   18          B+

In [32]:
new_df

Age Blood Group
Name                   
Rick     60          O+
Morty    10          O+
Summer   45          A-
Beth     18          B+

In [33]:
new_df.drop("Summer",axis=0)

Age Blood Group
Name                  
Rick    60          O+
Morty   10          O+
Beth    18          B+

In [2]:
import numpy as np
import pandas as pd
market_df = pd.read_csv('http://pythonhow.com/supermarkets.csv')
market_df

ID          Address           City  ... Country         Name Employees
0   1     3666 21st St  San Francisco  ...     USA      Madeira         8
1   2   735 Dolores St  San Francisco  ...     USA  Bready Shop        15
2   3      332 Hill St  San Francisco  ...     USA  Super River        25
3   4     3995 23rd St  San Francisco  ...     USA   Ben's Shop        10
4   5  1056 Sanchez St  San Francisco  ...     USA      Sanchez        12
5   6  551 Alvarado St  San Francisco  ...     USA   Richvalley        20

[6 rows x 7 columns]

In [3]:
market_df=market_df.set_index("ID")
market_df

Address           City  ...         Name Employees
ID                                  ...                       
1      3666 21st St  San Francisco  ...      Madeira         8
2    735 Dolores St  San Francisco  ...  Bready Shop        15
3       332 Hill St  San Francisco  ...  Super River        25
4      3995 23rd St  San Francisco  ...   Ben's Shop        10
5   1056 Sanchez St  San Francisco  ...      Sanchez        12
6   551 Alvarado St  San Francisco  ...   Richvalley        20

[6 rows x 6 columns]

In [6]:
market_df.iloc[:,3:]

Country         Name  Employees
ID                                
1      USA      Madeira          8
2      USA  Bready Shop         15
3      USA  Super River         25
4      USA   Ben's Shop         10
5      USA      Sanchez         12
6      USA   Richvalley         20

In [7]:
market_df.iloc[:3,3:]

Country         Name  Employees
ID                                
1      USA      Madeira          8
2      USA  Bready Shop         15
3      USA  Super River         25

In [8]:
market_df.loc[2:,:"Employees"]

Address           City  ...         Name Employees
ID                                  ...                       
2    735 Dolores St  San Francisco  ...  Bready Shop        15
3       332 Hill St  San Francisco  ...  Super River        25
4      3995 23rd St  San Francisco  ...   Ben's Shop        10
5   1056 Sanchez St  San Francisco  ...      Sanchez        12
6   551 Alvarado St  San Francisco  ...   Richvalley        20

[5 rows x 6 columns]

In [11]:
market_df.loc[4:,"Name":]

Name  Employees
ID                       
4   Ben's Shop         10
5      Sanchez         12
6   Richvalley         20

In [0]:
df1 = pd.DataFrame({                                       # Lets create 2 dataframes
    'id':[1,2,3,4,5],
    'name':['a','b','c','d','e'],
    'sub':['sub1','sub2','sub3','sub4','sub5']
})
df2 = pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['b','c','d','e','f'],
    'sub':['sub3','sub4','sub5','sub6','sub7']
})

In [13]:
print(df1)
print()
print()
print(df2)

   id name   sub
0   1    a  sub1
1   2    b  sub2
2   3    c  sub3
3   4    d  sub4
4   5    e  sub5


   id name   sub
0   1    b  sub3
1   2    c  sub4
2   3    d  sub5
3   4    e  sub6
4   5    f  sub7


In [18]:
pd.concat([df1,df2],axis=0)

id name   sub
0   1    a  sub1
1   2    b  sub2
2   3    c  sub3
3   4    d  sub4
4   5    e  sub5
0   1    b  sub3
1   2    c  sub4
2   3    d  sub5
3   4    e  sub6
4   5    f  sub7

In [19]:
print(pd.concat([df1,df2],axis=1))

   id name   sub  id name   sub
0   1    a  sub1   1    b  sub3
1   2    b  sub2   2    c  sub4
2   3    c  sub3   3    d  sub5
3   4    d  sub4   4    e  sub6
4   5    e  sub5   5    f  sub7


In [0]:
import pandas as pd
df1 = pd.DataFrame({                                       # Lets create 2 dataframes
    'emp_id':[1,2,3,4,5],
    'emp_name':['a','b','c','d','e'],
    'sub':['sub1','sub2','sub3','sub4','sub5']
})
df2 = pd.DataFrame({
    'dept_id':[1,2,3,4,5],
    'dept_name':['b','c','d','e','f'],
    'sub':['sub3','sub4','sub5','sub6','sub7']
})

In [21]:
print(df1)
print()
print(df2)

   emp_id emp_name   sub
0       1        a  sub1
1       2        b  sub2
2       3        c  sub3
3       4        d  sub4
4       5        e  sub5

   dept_id dept_name   sub
0        1         b  sub3
1        2         c  sub4
2        3         d  sub5
3        4         e  sub6
4        5         f  sub7


In [23]:
pd.merge(left=df1,right=df2,on="sub")

emp_id emp_name   sub  dept_id dept_name
0       3        c  sub3        1         b
1       4        d  sub4        2         c
2       5        e  sub5        3         d

In [25]:
pd.merge(left=df1,right=df2,on="sub",how="outer")

emp_id emp_name   sub  dept_id dept_name
0     1.0        a  sub1      NaN       NaN
1     2.0        b  sub2      NaN       NaN
2     3.0        c  sub3      1.0         b
3     4.0        d  sub4      2.0         c
4     5.0        e  sub5      3.0         d
5     NaN      NaN  sub6      4.0         e
6     NaN      NaN  sub7      5.0         f

In [26]:
df3 = pd.DataFrame({'id':[10],                             # Lets modify our row to a DataFrame
                    'name':['z'], 
                    'sub':['sub10']})
print(df3)

   id name    sub
0  10    z  sub10


In [27]:
print(df1)

   emp_id emp_name   sub
0       1        a  sub1
1       2        b  sub2
2       3        c  sub3
3       4        d  sub4
4       5        e  sub5


In [30]:
df4=df1
df5=df3
df4.append(df5,ignore_index=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,


emp_id emp_name    id name    sub
0     1.0        a   NaN  NaN   sub1
1     2.0        b   NaN  NaN   sub2
2     3.0        c   NaN  NaN   sub3
3     4.0        d   NaN  NaN   sub4
4     5.0        e   NaN  NaN   sub5
5     NaN      NaN  10.0    z  sub10

In [31]:
market_df

Address           City  ...         Name Employees
ID                                  ...                       
1      3666 21st St  San Francisco  ...      Madeira         8
2    735 Dolores St  San Francisco  ...  Bready Shop        15
3       332 Hill St  San Francisco  ...  Super River        25
4      3995 23rd St  San Francisco  ...   Ben's Shop        10
5   1056 Sanchez St  San Francisco  ...      Sanchez        12
6   551 Alvarado St  San Francisco  ...   Richvalley        20

[6 rows x 6 columns]

In [32]:
print(market_df["Employees"]>=15)
print(market_df["Employees"]<=25)

ID
1    False
2     True
3     True
4    False
5    False
6     True
Name: Employees, dtype: bool
ID
1    True
2    True
3    True
4    True
5    True
6    True
Name: Employees, dtype: bool


In [33]:
print(market_df[~(market_df["Employees"]>=15)])

            Address           City       State Country        Name  Employees
ID                                                                           
1      3666 21st St  San Francisco    CA 94114     USA     Madeira          8
4      3995 23rd St  San Francisco    CA 94114     USA  Ben's Shop         10
5   1056 Sanchez St  San Francisco  California     USA     Sanchez         12


In [34]:
print(market_df[(market_df["Employees"]>=15)])

            Address           City  ...         Name Employees
ID                                  ...                       
2    735 Dolores St  San Francisco  ...  Bready Shop        15
3       332 Hill St  San Francisco  ...  Super River        25
6   551 Alvarado St  San Francisco  ...   Richvalley        20

[3 rows x 6 columns]


In [38]:
print(market_df[(market_df["Employees"]<=25) & (market_df["State"]=="CA94119")])
print(market_df[~(market_df["Employees"]>=15) & (market_df["State"]!="CA94114")])

Empty DataFrame
Columns: [Address, City, State, Country, Name, Employees]
Index: []
            Address           City       State Country        Name  Employees
ID                                                                           
1      3666 21st St  San Francisco    CA 94114     USA     Madeira          8
4      3995 23rd St  San Francisco    CA 94114     USA  Ben's Shop         10
5   1056 Sanchez St  San Francisco  California     USA     Sanchez         12


In [42]:
print(market_df[(market_df["Employees"]<=15) & (market_df["State"]!="CA94114")])

            Address           City       State Country         Name  Employees
ID                                                                            
1      3666 21st St  San Francisco    CA 94114     USA      Madeira          8
2    735 Dolores St  San Francisco    CA 94119     USA  Bready Shop         15
4      3995 23rd St  San Francisco    CA 94114     USA   Ben's Shop         10
5   1056 Sanchez St  San Francisco  California     USA      Sanchez         12


In [0]:
company_df = {
    'Company':['Google','Google','Google','Microsoft','Microsoft','Microsoft'],
    'Year' : [2008,2009,2010,2008,2009,2010],
    'Revenue' : [11,15,16,9,12,14],
    'Employee' : [300,400,500,350,450,550]}

In [45]:
cmp_df=pd.DataFrame(company_df)
cmp_df

Company  Year  Revenue  Employee
0     Google  2008       11       300
1     Google  2009       15       400
2     Google  2010       16       500
3  Microsoft  2008        9       350
4  Microsoft  2009       12       450
5  Microsoft  2010       14       550

In [0]:
cmp_df.set_index(["Company","Year"],inplace=True)

In [47]:
cmp_df

Revenue  Employee
Company   Year                   
Google    2008       11       300
          2009       15       400
          2010       16       500
Microsoft 2008        9       350
          2009       12       450
          2010       14       550

In [48]:
print(cmp_df.loc["Google"])
print(cmp_df.loc["Google"].loc[2009])

      Revenue  Employee
Year                   
2008       11       300
2009       15       400
2010       16       500
Revenue      15
Employee    400
Name: 2009, dtype: int64


In [49]:
print(cmp_df.loc["Google"].loc[2010])

Revenue      16
Employee    500
Name: 2010, dtype: int64


In [50]:
print(cmp_df.xs("Microsoft",level="Company"))

      Revenue  Employee
Year                   
2008        9       350
2009       12       450
2010       14       550


In [52]:
print(cmp_df.xs(2009,level="Year"))

           Revenue  Employee
Company                     
Google          15       400
Microsoft       12       450


In [53]:
import seaborn as sns                                                               # Import seaborn library for dataset
import pandas as pd
tips = sns.load_dataset('tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4